### ISSUE TITLE
Crash in any seige battle

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#2709]
**Describe the bug**
I found this new fatal bug in latest daily branch. 
If in a seige war, if player is defender, it will be crash immediately.
If player is attacker, it will be stuck after arrow tower's action.

**Did it work earlier?**
It occurs after updating new build, I just wanna test backpack GUI.

**Version**
 - OS: Windows
 - Version: 1.4.0 updated this day

**Comment by rilian-la-te** [comment]
@by003 fort, citadel or castle?

@IvanSavenko did you checked moats after your battle changes?

**Comment by by003** [comment]
> @by003 fort, citadel or castle?

Actually it crashes in citadel and castle

**Comment by rilian-la-te** [comment]
@IvanSavenko looks like related to https://github.com/vcmi/vcmi/issues/2694, but issue when moat caster try to cast moat opening battle spell.

**Comment by by003** [comment]
I didn't find this crash when I put https://github.com/vcmi/vcmi/issues/2694 last time. It only cannot use opening battle spells.

**Comment by rilian-la-te** [comment]
@by003 moat creator is also an opening battle spell.

**Comment by by003** [comment]
I have tested opening battle spell, it will not crash if it can cast or not (https://github.com/vcmi/vcmi/issues/2694). Only crashes in seige battle with citadel and castle.

**Comment by IvanSavenko** [comment]
Fixed in #2686

**Comment by by003** [comment]
> Fixed in #2686

Sorry, it still occurs in the version: 
![image](https://github.com/vcmi/vcmi/assets/127420617/1e10e3e6-a148-4a39-b7f6-0ba48e7249d1)

Please notice it if something wrong.

**Comment by by003** [comment]
Tried many times, it crashes in siege battle.
![image](https://github.com/vcmi/vcmi/assets/127420617/b023c9a3-9e79-45b8-91fa-23ebc494cf7b)

**Comment by misiokles** [comment]
In latest build (develop-24ad06b) I get regular crashes during fights in banks. Not at the beginning, not at end, just random crashes in random moments.
![image](https://github.com/vcmi/vcmi/assets/29593042/83a8a819-efbb-4f88-884f-cb1d3fe64f6d)

 
[logz.zip](https://github.com/vcmi/vcmi/files/12563534/logz.zip)

**Comment by misiokles** [comment]
Oh,, not only banks, neutral units also.
[crash.zip](https://github.com/vcmi/vcmi/files/12563592/crash.zip)
Load crash save and provoke fight with nearest Gorgons.

**Comment by by003** [comment]
> Load crash save and provoke fight with nearest Gorgons.

I tried to use resurrect ability from archangel, and it crashes too.
