### ISSUE TITLE
I can't attack,defence,retreat,wait etc.

### ISSUE THREAD

**Issue by LordIofIThunder** [vcmi/vcmi#3020]
**Describe the bug**
It seems that i can't do anything except cancel spells even if i didn't choose any of them.This thing also happened before but without the centaur doing that.

**Game logs**
Please attach game logs: `![VCMI_Server_log.txt](https://github.com/vcmi/vcmi/files/12837682/VCMI_Server_log.txt)

`, `![VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12837683/VCMI_Client_log.txt)

` etc.

**To Reproduce**
1. So basically all you need to do is get in a battle with some random creatures on the map.There's no 100% to happen.

**Expected behavior**
I should be capable to attack,defence etc.

**Actual behavior**
All i can do is just cancel spells without to have to choose one.
**Did it work earlier?**
Except the centaur this behaviour happened before.

**Version**
 - OS: [e.g.Android]
 - Version: [VCMI version 1.4.0]

**Additional context**
https://github.com/vcmi/vcmi/assets/146068046/35645a6a-341d-4d76-9abe-db48e826f551

**Comment by misiokles** [comment]
Probably mixed/messed files between stable 1.3.2 and develop 1.4 vestion. The same with mods.

**Comment by LordIofIThunder** [comment]
This also happend in vcmi 1.3.2 before installing 1.4.0 on my device.The only difference is that not a single creature could move like the centaur.And i don't think the mods are responsible because i also played without a single one and it give the same behaviour.

**Comment by misiokles** [comment]
Try to unistall and install again vcmi-extras

**Comment by LordIofIThunder** [comment]
Done.thanks for the fast answer<3

**Comment by by003** [comment]
I am sure it still occurs in 1.3.2 and really rare, but we cannot ignore it even once.

**Comment by nullkiller** [comment]
So was it resolved?
