### ISSUE TITLE
Validate mods type "graphical" to contain only cosmetic changes

### ISSUE THREAD

**Issue by thiscris** [vcmi/vcmi#3666]
**Describe your proposal**
Graphical mods are the easiest way to highlight the modular capabilities of VCMI without affecting gameplay. Some of the mods available in the launcher give the impression that they are purely cosmetic (based on their title, description and type) but include changes that impact the game balance.
It would be much better if the community simply didn't label as "graphical" mods that include changes in the gameplay or separate those changes in their own mods.
In order to reduce the need for manual verification with each upload, maybe there could be an automatic check to confirm if the files in the mod are only .bmp or .def files. Alternatively, if there are ,json files, there could be a whitelist of approved parameters that could be included in those json files (e.g. "animation" - allowed ; "attack" - not allowed)

**Additional context**
"Autumn Rampart" changes the stats for dwarfs and battle dwarfs.
"Sand Tower" changes the terrain of the faction from snow to sand and adds gold golems as upgrades inside the town.
Those are balancing changes that were not mentioned in the mods description and do not belong in mods of type "Graphical".

**Comment by GeorgeK1ng** [comment]
Fixed in Alternate Town screens 1.0.2 https://github.com/vcmi-mods/alternate-townscreens

**Comment by IvanSavenko** [comment]
This was about having this enforced / validated on engine level, not about specific mod. So issue is still valid, even if currently offending mods are fixed

**Comment by GeorgeK1ng** [comment]
Ah, this is about adding schema validation for mod types.
