### ISSUE TITLE
Crash on AI turn - Attempt to visit object that is being visited by another hero!

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#4598]
msvs, current develop 1.6.0.7209969d9dd239ac73f9acf045f99081a2df92cd

crash happens on green AI

> [2024-Sep-15 09:08:36.542512] DEBUG [AIGateway::makeTurn] ai - Moving hero Дейс to tile (105 72 1)
> [2024-Sep-15 09:08:36.542512] DEBUG [AIGateway::requestActionASAP::whatToDo] ai - I'll answer the query 443 giving the choice 0
> [2024-Sep-15 09:08:36.543511] ERROR [runServer] global - 
> 
> | Player "GREEN" has to answer queries before attempting any further actions.
> 
> | Top Query: "A query of type 'class CHeroLevelUpDialogQuery' and qid = 443 affecting player GREEN, "
> 
> 
> [2024-Sep-15 09:08:36.543511] DEBUG [AIGateway::requestActionASAP::whatToDo] ai - Attempted answering query 443 - Hero Дейс got level 2. Request id=449. Waiting for results...
> [2024-Sep-15 09:08:36.545511] DEBUG [runServer] global - Hero hero.core.dace.name visits Kal Ort Xen, Подземелье (98)
> [2024-Sep-15 09:08:36.545511] ERROR [runNetwork] network - System message: Server encountered a problem: 
> 
> | Player "GREEN" has to answer queries before attempting any further actions.
> 
> | Top Query: "A query of type 'class CHeroLevelUpDialogQuery' and qid = 443 affecting player GREEN, "
> 
> 
> [2024-Sep-15 09:08:36.545511] ERROR [runServer] global - Attempt to visit object that is being visited by another hero!
> [2024-Sep-15 09:08:36.549508] DEBUG [MainGUI] global - totalRedraw requested!
> [2024-Sep-15 09:08:36.553610] ERROR [runServer] global - Disaster happened.

save [crash.zip](https://github.com/user-attachments/files/17004799/crash.zip)
log [VCMI_Client_log.txt](https://github.com/user-attachments/files/17004812/VCMI_Client_log.txt)
dump https://drive.google.com/file/d/1BDZ2eLV2JCn5gm0q-rEL8CoUGaKnVVbU/view?usp=drive_link

**Comment by IvanSavenko** [comment]
Should be fixed in #4609

**Comment by Povelitelh3** [comment]
> Should be fixed in #4609

still crashed in last develop 658c359bc7454b00e424f1c3fb4597f43d062179
https://drive.google.com/file/d/1XTD3kJf52VqQcmCKE42rSaDi35ztG0sq/view?usp=drive_link

**Comment by Povelitelh3** [comment]
Looks like one more case [TestCRash.zip](https://github.com/user-attachments/files/17078441/TestCRash.zip)
