### ISSUE TITLE
VCMI Freeze when trying to load custom HotA campaign - Warcraft III: Reign of Chaos

### ISSUE THREAD

**Issue by GeorgeK1ng** [vcmi/vcmi#6299]
When I try to load in latest develop this campaign, VCMI freeze and then crash / disappear on latest develop. I have also tried to resave this campaign with HotA campaign editor, but it doesn't change anything. It acts same. Seems it always loads 0 maps, but there are 12 of them.

Great Campaign - 12 maps
At the same time, he conflicts with his former friend and supervisor Uther. After the slaughter, Arthas travels to the lands of Northend with Captain, where Mal Ganis promised him a meeting. There he meets Muradin, king of the mountains. He came to study the legend of the Blade of Frost.

https://www.maps4heroes.com/forum/opinions.php?map_id=1758&game=3

LOG:

[2025-Nov-06 16:51:06.213422] TRACE [MainGUI] global - loading C:\Users\Administrator\Documents\My Games\vcmi\Maps\Warcraft III.h3c
[2025-Nov-06 16:51:06.216414] TRACE [MainGUI] global - Campaign MAPS/WARCRAFT III: map 19 (0 scenarios), music theme: GoodTheme
[2025-Nov-06 16:51:06.216414] TRACE [MainGUI] network - Sending a pack of type struct LobbySetCampaign
[2025-Nov-06 16:51:06.217415] TRACE [runServer] network - Received CPack of type struct LobbySetCampaign
[2025-Nov-06 16:51:06.217415] TRACE [runServer] network - Sending a pack of type struct LobbySetCampaign
[2025-Nov-06 16:51:06.217415] TRACE [runServer] network - Sending a pack of type struct LobbyUpdateState
[2025-Nov-06 16:51:06.217415] TRACE [runNetwork] network - Received CPack of type struct LobbySetCampaign
[2025-Nov-06 16:51:06.217415] TRACE [runNetwork] network - Received CPack of type struct LobbyUpdateState
[2025-Nov-06 16:51:06.229381] TRACE [runNetwork] global - Loading music file MUSIC/GoodTheme
[2025-Nov-06 16:51:06.230379] TRACE [runNetwork] global - loading C:\Users\Administrator\Documents\My Games\vcmi\mp3\GoodTheme.mp3
[2025-Nov-06 16:51:06.230379] TRACE [runNetwork] global - Stopping music file Music/MainMenu at 8.199000

**Comment by GeorgeK1ng** [comment]
There is another report with this campaigns https://www.maps4heroes.com/forum/opinions.php?map_id=2565&game=3 which require this mapping 51 - https://github.com/vcmi-mods/horn-of-the-abyss/blob/9e378dc388c75a184aa81137bf1ff9869bccdd4b/mods/mapSupport/mod.json#L2314, when I uncomment them and try it again, then it fails on **Error: Failed to process campaign MAPS/KING OF THE KNIGHT: The end of the stream was reached unexpectedly. The stream has a length of 4100 and the current reading position is 862466986. The client wanted to read 862465592 bytes.**

**Comment by IvanSavenko** [comment]
Should be resolved in 1.8 - campaigns from hota 1.8 are now supported

**Comment by GeorgeK1ng** [comment]
Will try to test, but campaign from first post was not HotA 1.8 it was added in 2024.

**Comment by GeorgeK1ng** [comment]
I have just tested on latest VCMI on Android that Warcraft (https://www.maps4heroes.com/forum/opinions.php?map_id=1758&game=3) campaign and VCMI still crashes.

And this campaign will be probably same, needs uncomment 51 video mapping https://github.com/vcmi-mods/horn-of-the-abyss/blob/9e378dc388c75a184aa81137bf1ff9869bccdd4b/mods/mapSupport/mod.json#L2314 and then will probably crash too as it's 2024 too https://www.maps4heroes.com/forum/opinions.php?map_id=2565&game=3 

Also would be great it it won't crash when video mapping is missing, just not display it. And write it to log or similar approach.
